name: EPG Update

on:
  push:
  schedule:
    - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: EPG Update
      run: |
        rm -f e.xml && wget https://raw.githubusercontent.com/Meroser/IPTV/main/tvxml.xml -O 112.xml
        git config --global user.name lizanyang3
        git config --global user.email 1072400891@qq.com
        git add 112.xml
        git commit -m "Update 112.xml"
        git push -f origin main
